name: CI for Flutter & Python App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Flake8 (Code Quality Check)
        run: |
          flake8 backend --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Backend Unit Tests
        run: |
          pytest backend/tests

  flutter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Analyze Flutter Code
        run: flutter analyze
        working-directory: frontend

      - name: Run Flutter Unit Tests
        run: flutter test
        working-directory: frontend
